- name: minemeld playbook
  hosts: 127.0.0.1 minemeld-dev-1604
  connection: local
  become_method: sudo
  become: true

  vars:
    minemeld_version: develop
    file_permissions: 'u=rwX,g=rwX,o=rX'
  # uncomment the following to install stable
  # minemeld_version: master
  # group_permissions: 'u=rwX,g=rX,o=rX'
  # remove comment to set custom repositories
  # core_repo: "https://github.com/jtschichold/minemeld-core.git"
  # prototype_repo: "https://github.com/jtschichold/minemeld-node-prototypes.git"
  # webui_repo: "https://github/jtschichold/minemeld-webui.git"

  pre_tasks:
    - name: "Check for Vagrant"
      stat:
        path: /vagrant
      register: vagrant
    - name: "Install required packages"
      apt:
        name: "{{ item }}"
      with_items:
        - python-setuptools
        - python-pip
        - gcc
        - libffi-dev
        - libssl-dev
      when: vagrant.stat.isdir is defined and vagrant.stat.isdir

  roles:
  - infrastructure
  - minemeld
